### ISSUE TITLE
Timeseries simulation not working with runpm_dc_opf()

### ISSUE THREAD

**Issue by christoph-weyhing** [e2nIEE/pandapower#1059]
When I run a DCOPF with 
`run_timeseries(net, time_steps, continue_on_divergence=True, verbose=True, recycle=False, run=pp.runpm_dc_opf)`

I get the following error:

`Progress: |████████████--------------------------------------| 25.0% CompleteTraceback (most recent call last):

  File "C:\Users\s792\Documents\Git_MathEnergy_PyBench\MathEnergy_PyBench\master_thesis_christoph\future_scenario_NEP_C2030\nepC2030_run.py", line 93, in <module>
    run_timeseries(net, time_steps, continue_on_divergence=True, verbose=True, recycle=False, run=pp.runpm_dc_opf)

  File "C:\Users\s792\anaconda3\envs\gitpandapower\lib\site-packages\pandapower\pandapower\timeseries\run_time_series.py", line 348, in run_timeseries
    run_loop(net, ts_variables, **kwargs)

  File "C:\Users\s792\anaconda3\envs\gitpandapower\lib\site-packages\pandapower\pandapower\timeseries\run_time_series.py", line 320, in run_loop
    run_time_step(net, time_step, ts_variables, run_control_fct, output_writer_fct, **kwargs)

  File "C:\Users\s792\anaconda3\envs\gitpandapower\lib\site-packages\pandapower\pandapower\timeseries\run_time_series.py", line 121, in run_time_step
    run_control_fct(net, run_control=False, ctrl_variables=ts_variables, **kwargs)

  File "C:\Users\s792\anaconda3\envs\gitpandapower\lib\site-packages\pandapower\pandapower\control\run_control.py", line 260, in run_control
    control_implementation(net, controller_order, ctrl_variables, max_iter, **kwargs)

  File "C:\Users\s792\anaconda3\envs\gitpandapower\lib\site-packages\pandapower\pandapower\control\run_control.py", line 194, in control_implementation
    ctrl_variables = evaluate_net_fct(net, levelorder, ctrl_variables, **kwargs)

  File "C:\Users\s792\anaconda3\envs\gitpandapower\lib\site-packages\pandapower\pandapower\control\run_control.py", line 160, in _evaluate_net
    run_funct(net, **kwargs)  # run can be runpp, runopf or whatever

TypeError: runpm_dc_opf() got an unexpected keyword argument 'run_control'`

I tried pandapower 2.4.0 and right now I am using the latest commit from the develop branch, but with both versions I get the same error.

**Comment by rbolgaryn** [comment]
That's definitely an error in the code
