### ISSUE TITLE
power flow configuration

### ISSUE THREAD

**Issue by hitchenzhe** [e2nIEE/pandapower#1278]
Hi guys, I want to know what happened to my pandapower. Any environment issue? I just run a simple power flow and return the error.

`import os
import numpy as np
import numpy.random as npr
import pandas as pd
import pickle
import copy
import cvxpy as cp
import scipy.io as sio
import cmath
import time
import matplotlib.pyplot as plt
import cmath
start = time.time()   
import numpy as np
from enum import IntEnum
class Cols(IntEnum):
    Vmag = 0
    ReV = 1
    ImV = 2
    Pnetinj = 3
    Qnetinj = 4

import pandapower.networks as pn
import pandapower as pp

net = pn.case33bw()

pp.runpp(net)
TypeError: expected dtype object, got 'numpy.dtype[int64]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-3-955fd462a95e>", line 1, in <module>
    pp.runpp(net)

  File "C:\Users\zhech\Anaconda3\lib\site-packages\pandapower\run.py", line 225, in runpp
    _powerflow(net, **kwargs)

  File "C:\Users\zhech\Anaconda3\lib\site-packages\pandapower\powerflow.py", line 75, in _powerflow
    result = _run_pf_algorithm(ppci, net["_options"], **kwargs)

  File "C:\Users\zhech\Anaconda3\lib\site-packages\pandapower\powerflow.py", line 153, in _run_pf_algorithm
    result = _run_newton_raphson_pf(ppci, options)

  File "C:\Users\zhech\Anaconda3\lib\site-packages\pandapower\pf\run_newton_raphson_pf.py", line 51, in _run_newton_raphson_pf
    ppci, success, iterations = _run_ac_pf_without_qlims_enforced(ppci, options)

  File "C:\Users\zhech\Anaconda3\lib\site-packages\pandapower\pf\run_newton_raphson_pf.py", line 123, in _run_ac_pf_without_qlims_enforced
    ppci, Ybus, Yf, Yt = _get_Y_bus(ppci, options, makeYbus, baseMVA, bus, branch)

  File "C:\Users\zhech\Anaconda3\lib\site-packages\pandapower\pf\run_newton_raphson_pf.py", line 79, in _get_Y_bus
    Ybus, Yf, Yt = makeYbus(baseMVA, bus, branch)

  File "C:\Users\zhech\Anaconda3\lib\site-packages\pandapower\pf\makeYbus_numba.py", line 166, in makeYbus
    Yx, Yj, Yp, nnz = gen_Ybus(Yf_x, Yt_x, Ysh, col_Y, f, t, np.argsort(f), np.argsort(t), nb, nl,

SystemError: CPUDispatcher(<function gen_Ybus at 0x0000018993652EE0>) returned a result with an error set`

**Comment by hitchenzhe** [comment]
Done by updating packages
