### ISSUE TITLE
[bug] KeyError: 1634 when running the IEEE LV test feeder

### ISSUE THREAD

**Issue by CoolJoe86** [e2nIEE/pandapower#1915]
## Problem Description
Hello, I am receiving the following error when I try to run the IEEE 2015 LV feeder model.

KeyError: 1634

### What steps reproduce the problem?

I am trying to run the IEEE 2015 Test Feeder Cases - European Low Voltage Test Feeder using the included time-series data (https://cmte.ieee.org/pes-testfeeders/resources/). I create the grid using the parameters provided by IEEE, and I run the provided time-series data on the grid. I do divide lengths to obtain distance in km, and loads to obtain power in MW. Otherwise, I use the values in the IEEE document.

### What is the expected output? What do you see instead?
The time-series simulation does no resolve.

### Paste Traceback/Error Below (if applicable)
```python-traceback

> Progress: |█-------------------------------------------------| 2.3% CompleteTraceback (most recent call last):

  File "C:\Users\soch\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3803, in get_loc
    return self._engine.get_loc(casted_key)

  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item

  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item

KeyError: 1634


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\soch\AppData\Local\Temp\ipykernel_12428\1341278408.py", line 1, in <module>
    Run()

  File "c:\users\soch\onedrive - hanzehogeschool groningen\no gizmos\model\nogizmos.py", line 128, in Run
    net = Run_Model(net, load_pattern, gen_pattern, output_dir)

  File "c:\users\soch\onedrive - hanzehogeschool groningen\no gizmos\model\nogizmos.py", line 580, in Run_Model
    run_timeseries(net, time_steps=n_ts, continue_on_divergence=True)

  File "C:\Users\soch\anaconda3\lib\site-packages\pandapower\timeseries\run_time_series.py", line 346, in run_timeseries
    run_loop(net, ts_variables, **kwargs)

  File "C:\Users\soch\anaconda3\lib\site-packages\pandapower\timeseries\run_time_series.py", line 318, in run_loop
    run_time_step(net, time_step, ts_variables, run_control_fct, output_writer_fct, **kwargs)

  File "C:\Users\soch\anaconda3\lib\site-packages\pandapower\timeseries\run_time_series.py", line 117, in run_time_step
    control_time_step(ts_variables['controller_order'], time_step)

  File "C:\Users\soch\anaconda3\lib\site-packages\pandapower\timeseries\run_time_series.py", line 84, in control_time_step
    ctrl.time_step(net, time_step)

  File "C:\Users\soch\anaconda3\lib\site-packages\pandapower\control\controller\const_control.py", line 155, in time_step
    self.values = self.data_source.get_time_step_value(time_step=time,

  File "C:\Users\soch\anaconda3\lib\site-packages\pandapower\timeseries\data_sources\frame_data.py", line 49, in get_time_step_value
    res = self.df.loc[time_step, profile_name]

  File "C:\Users\soch\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1067, in __getitem__
    return self._getitem_tuple(key)

  File "C:\Users\soch\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1247, in _getitem_tuple
    return self._getitem_lowerdim(tup)

  File "C:\Users\soch\anaconda3\lib\site-packages\pandas\core\indexing.py", line 967, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)

  File "C:\Users\soch\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1312, in _getitem_axis
    return self._get_label(key, axis=axis)

  File "C:\Users\soch\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1260, in _get_label
    return self.obj.xs(label, axis=axis)

  File "C:\Users\soch\anaconda3\lib\site-packages\pandas\core\generic.py", line 4056, in xs
    loc = index.get_loc(key)

  File "C:\Users\soch\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    raise KeyError(key) from err

KeyError: 1634

```

## Versions

* pandapower version: 2.7.0
* pandas version:  1.5.2
* networkx version: 2.8.4
* scipy version: 1.10.0
* numpy version: 1.23.5
* packaging version: 22.0
* tqdm version: 4.64.1
* deepdiff version: do not have
* Operating System name/version: Windows 10

Thank you for any help.
Christian

**Comment by CoolJoe86** [comment]
Well, I resolved the problem. Kind of dumb, but I had some stray data at the bottom of the load profile csv. This was causing my load profile to be huge and filled with lots of zeros, which caused the error.
