### ISSUE TITLE
[bug] ModuleNotFoundError: No module named 'pytest'

### ISSUE THREAD

**Issue by meyer89** [e2nIEE/pandapower#1983]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports
* [x] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html) 
* [x] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use
* [x] Reproduced the issue after updating with `pip install --upgrade pandapower` (or `git pull`)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted interpreter
    * [x] Checked the pythonpath
* [x] Completed the **Problem Description**, **What steps reproduce the problem** and **Versions** sections below

## Problem Description

After updating pandapower to 2.12.0, the import fails with the error ModuleNotFoundError: No module named 'pytest'
This error does not exist in the previous version 2.11.2.

### What steps reproduce the problem?

1. Install pandapower 2.12.0 in a new virtualenv with `pip install --upgrade pandapower`
2. Import pandapower with `import pandapower as pp`

### What is the expected output? What do you see instead?

Expected output: _nothing_
Output: `ModuleNotFoundError: No module named 'pytest'`

### Paste Traceback/Error Below (if applicable)

```python-traceback

> import pandapower as pp
matplotlib could not be imported. It is required for many plotting functions. 
Thus, this might lead to errors with some plotting functions. To install all pandapower dependencies, pip install pandapower['all'] can be used.
Traceback (most recent call last):
  File "/snap/pycharm-community/327/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/snap/pycharm-community/327/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/xxx/PycharmProjects/my-project/venv/lib/python3.10/site-packages/pandapower/__init__.py", line 35, in <module>
    import pandapower.test
  File "/snap/pycharm-community/327/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/xxx/PycharmProjects/my-project/venv/lib/python3.10/site-packages/pandapower/test/__init__.py", line 7, in <module>
    from pandapower.test.conftest import *
  File "/snap/pycharm-community/327/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/xxx/PycharmProjects/my-project/venv/lib/python3.10/site-packages/pandapower/test/conftest.py", line 8, in <module>
    import pytest
  File "/snap/pycharm-community/327/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'pytest'

```

## Versions

* pandas version: 2.0.0
* networkx version: 3.0
* scipy version: 1.10.1
* numpy version: 1.24.2
* packaging version: 23.0
* tqdm version: 4.64.1
* deepdiff version: 6.2.3
* Operating System name/version: Ubuntu 22.04 LTS

## Labels (if access available)
n/a

**Comment by ensslen** [comment]
I'm seeing this same behaviour on OS X 13.3 Python 3.8.16, and on Python 3.8.12 on whatever linux-flavor Google's managed Apache Airflow (Google Cloud Composer) runs.

**Comment by SteffenMeinecke** [comment]
Should be fixed now. Please reopen if the problem occurs again.
