### ISSUE TITLE
[bug] Missing dependency pytest

### ISSUE THREAD

**Issue by BDonnot** [e2nIEE/pandapower#1988]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports
* [X]  Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html) 
* [X]  Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use
* [X]  Reproduced the issue after updating with `pip install --upgrade pandapower` (or `git pull`)
* [X]  Tried basic troubleshooting (if a bug/error)
    * [X]  Restarted interpreter
    * [X]  Checked the pythonpath
* [X]  Completed the **Problem Description**, **What steps reproduce the problem** and **Versions** sections below

## Problem Description

Related (but not the same) to #1985 I also found out a missing dependency for pandapower version 2.12 (still the CI of some of my projects). This time it's not related to a python version, but the "pytest" package is missing (in the setup.py / setup.cfg) and prevents the use of pandapower when it's not installed.

This problem did not appear with previous version of pandapower.

### What steps reproduce the problem?
Run the following script:

```bash
python3 -m virtualenv venv_test_pp
source venv_test_pp/bin/activate
pip install --upgrade pandapower
python -c "import pandapower as pp"
```

### What is the expected output? What do you see instead?

This results in the error:

```
matplotlib could not be imported. It is required for many plotting functions. 
Thus, this might lead to errors with some plotting functions. To install all pandapower dependencies, pip install pandapower['all'] can be used.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "venv_test_pp/lib/python3.8/site-packages/pandapower/__init__.py", line 35, in <module>
    import pandapower.test
  File "venv_test_pp/lib/python3.8/site-packages/pandapower/test/__init__.py", line 7, in <module>
    from pandapower.test.conftest import *
  File "venv_test_pp/lib/python3.8/site-packages/pandapower/test/conftest.py", line 8, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "venv_test_pp/lib/python3.8/site-packages/pandapower/__init__.py", line 35, in <module>
    import pandapower.test
  File "venv_test_pp/lib/python3.8/site-packages/pandapower/test/__init__.py", line 7, in <module>
    from pandapower.test.conftest import *
  File "venv_test_pp/lib/python3.8/site-packages/pandapower/test/conftest.py", line 8, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'

```

## Versions

* pandas version: 
* networkx version: 
* scipy version: 
* numpy version: 
* packaging version: 
* tqdm version: 
* deepdiff version: 
* Operating System name/version: ubuntu 20.04

It does not depends on any of these packages, the bug is a missing package in setup.py / setup.cfg or when importing pandapower (in `__init__.py` line 35) :

```python
try:
    import pandapower.test
except ImportError:
    # pytest is not installed, the "test" module will not be available
    pass
```

## Labels (if access available)
* [X] Choose a `labels` at the right side (e.g. `bug`, `controller`, `OPF`...)

**Comment by BDonnot** [comment]
closing due to duplicate :  #1983

(I did a wrong search when looking for similar issues)
